config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get '/pets', to: 'pets#index', as: 'pets'

  # get '/pets/new', to: 'pets#new', as: 'new_pet'
  # post '/pets', to: 'pets#create'

  # get '/pets/:id', to: 'pets#show', as: 'pet'

  # get '/pets/:id/edit', to: 'pets#edit', as: 'edit_pet'
  # patch '/pets/:id', to: 'pets#update'

  # delete '/pets/:id', to: 'pets#destroy'

  resources :pets #, only: [:index, :show, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ['elephant', 'dog', 'cat', 'rabbit', 'bat']
  validates :name, presence: true
  # elephant, cat, dog
  validates :species, inclusion: { in: Pet::SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pets_path
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet.id) #=>/pets/pet_id
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets1092</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for(pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :found_on %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.submit %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<h1>All pets</h1>

<ul class='list-group'>
  <% @pets.each do |pet| %>
    <li class='list-group-item'>
      <%= link_to pet.name, pet_path(pet) %>
      <%= link_to 'Destroy this pet', pet_path(pet), data: { turbo_method: :delete } %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add a pet', new_pet_path, class: 'btn btn-primary' %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>

<ul>
  <li>Species: <%= @pet.species %></li>
  <li>Address: <%= @pet.address %></li>
  <li>Found on: <%= @pet.found_on %></li>
</ul>

<%= link_to 'Back to all pets', pets_path, class: 'btn btn-primary' %>
<%= link_to 'Edit pet', edit_pet_path(@pet), class: 'btn btn-warning' %>